pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
                sh 'npm run build'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Manual Approval') {
            steps {
                input message: 'Lanjutkan ke tahap "Deploy" to continue ?'
            } 
        }
        stage('Deploy') {
            steps {
            sleep(time: 1, unit: 'MINUTES')
            echo 'Finish with access at https://a428-cicd-labs-production.up.railway.app/'

            }
        }
    }
}