pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Manual Approval') {
            steps {
                input message: 'Lanjutkan ke tahap Deploy" to continue)'
            }
        }
        stage('Deploy') {
            steps {
                sleep(time: 1, unit: 'MINUTES')
                // sh './jenkins/scripts/deliver.sh'
                // sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
